<!--Messages d'erreurs / avertissements-->
<?php if (isset($_GET['message'])): ?>
    <p class="announcement"><?= $_GET['message'] ?></p>
<?php endif; ?>

<?php if(!empty($user) || $user != false) : ?>
<section id="profile-aside">
    <h2 class="section-title-admin">Identité</h2>
    <div class="img-and-pseudo">
        <img src="public/images/avatars/<?= htmlspecialchars($user['pdp']) ?>" alt="<?= htmlspecialchars($user['pseudo']) ?>" class="profile-picture-medium">
        <h3><?= htmlspecialchars($user['pseudo']) ?></h3>
    </div>
    <div class="user-infos">
        <ul>
            <li><span>Identifiant</span> <?= $user['id_user'] ?></li>
            <li><span>Email</span> <?= $user['mail'] ?></li>
        </ul>
        <ul>
             <?php if (empty($user['nom'])): ?>
             <li class="red-admin"><span>Nom</span> Non renseigné</li>
             <?php else: ?>
             <li><span>Nom</span> <?= $user['nom'] ?></li>
             <?php endif; ?>
             
             <?php if (empty($user['prenom'])): ?>
             <li class="red-admin"><span>Prénom</span> Non renseigné</li>
             <?php else: ?>
             <li><span>Prénom</span> <?= $user['prenom'] ?></li>
             <?php endif; ?>
             
             <?php if (empty($user['tel'])): ?>
             <li class="red-admin"><span>Téléphone</span> Non renseigné</li>
             <?php else: ?>
             <li><span>Téléphone</span> <?= $user['tel'] ?></li>
             <?php endif; ?>
             
             <?php if (empty($user['anniversaire'])): ?>
             <li class="red-admin"><span>Anniversaire</span> Non renseigné</li>
             <?php else: ?>
             <li><span>Anniversaire</span> <?= $user['anniversaire'] ?></li>
             <?php endif; ?>
        </ul>
        <div class="boutons-admin">
            <a href="index.php?action=send-admin-notif&id=<?= $user['id_user'] ?>" class="fake-button">Envoyer un avertissement</a>
            <a href="index.php?action=delete-user&id=<?= $user['id_user'] ?>" class="fake-button">Supprimer le compte (définitif)</a>
        </div>
    </div>
</section>
<section id="profile-comments">
        <h2 class="section-title-admin">Commentaires</h2>
        <div id="comments-profile">
            <?php if (empty($comments)): ?>
            <p class="announcement">Aucun commentaire</p>
            <?php elseif(!empty($comments)): ?>
                <?php foreach($comments as $comment) : ?>
                    <div class="one-comment-admin">
                        <div class="comment-main-admin">
                            <p><?= $comment['contenu'] ?></p>
                            <small>Le <?= $comment['date'] = date("d/m/Y à H:i", strtotime($comment['date'])); ?></small>
                        </div>
                        <a href="index.php?action=manage-review&id=<?= $comment['id_review'] ?>&user=<?= $comment['id_user'] ?>" class="fake-button">Consulter</a>
                    </div>
                <?php endforeach; ?>
        <?php endif; ?>
        </div>
</section>
<?php else: ?>
<p class="red-admin">Aucun utilisateur trouvé</p>
<?php endif; ?>