<!--Page d'accueil lorsqu'on est pas connecté-->
<?php if(!$this -> is_connect()) : ?>
    <section class = "main_container">
        <div class="formulaire">
            <form action="index.php?action=create-account" method="post" id="form-sensible" data-inputs-required="4" class="standard-form">
                <fieldset>
                    <h2 class="legend">Création d'un compte</h2>
                    <?php if(!empty($messages)) : ?>
                        <?php foreach($messages as $msg) : ?>
                             <p><?= $msg ?> </p>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <?php if(isset($message)) : ?>
                        <p><?= $message ?> </p>
                    <?php endif; ?>
                    <div class="input-span">
                        <div class="input pseudo-form">
                            <input type="text" name="pseudo" class="donnee" id="pseudo"/>
                            <label for="pseudo" class="label">Pseudo</label>
                        </div>
                        <div class="error-pseudo"></div>
                    </div>
                    <div class="input-span">
                        <div class="input email">
                            <input type="email" name="mail" class="donnee" id="mail"/>
                            <label for="mail" class="label">Email</label>
                        </div>
                        <div class="error-email"></div>
                    </div>
                    <div class="input-span">
                        <div class="input anniversaire">
                            <input type="date" name="anniversaire" id="anniversaire"/>
                            <label for="anniversaire" class="label">Date de naissance </label>
                        </div>
                        <div class="error-anniversaire"></div>
                    </div>
                    <div class="input-span">
                        <div class="input password">
                            <input type="password" name="mdp" class="donnee" id="mdp"/>
                            <label for="mdp" class="label">Mot de passe</label>
                        </div>
                        <div class="error-password"></div>
                    </div>
                    <input type="hidden" name="token" value="<?= $_SESSION['csrf_token'] ?>">
                    <div class="boutons-disconnected">
                        <button id="bouton" class="disconnected-button">Créer un compte</button>
                    </div>
                </fieldset>
            </form>
        </div>
    </section>
<?php endif; ?>
<script type="module" src="public/js/valid_form.js"></script>