<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="the red curtain">
    <title>the red curtain</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&family=Tektur&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script
    	  src="https://code.jquery.com/jquery-3.4.1.min.js"
    	  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
    	  crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="public/css/style.css" type="text/css" />
    <link rel="stylesheet" href="public/css/normalize.css" type="text/css" />
    <link rel="icon" type="image/x-icon" href="public/images/red_logo.png">
</head>
<?php if(!$this -> is_connect()): ?>
<body class="disconnected-background">
<?php elseif ($this->is_connect()): ?>
<body class="connected-background">
<?php endif; ?>
<header class="header">
    <!--Si l'utilisateur est connecté-->
    <?php if($this -> is_connect()) : ?>
        <!--Logo rouge-->
        <div class="for-flex">
            <a href="index.php?action=feed"><img src="public/images/red_logo_title.png" alt="Logo" id="logo"></a>
            <button id="drop-down-menu" class="check connected"><i id="menu-icon" class="fa-solid fa-bars"></i></button>
        </div>
         <nav class="hidden-nav">
            <ul class="menu">
                <li><a href="index.php?action=see-notifs" class="notification">Notifications<span id="notif-counter"><?= $_SESSION['user']['notifs'] ?></span></a></li>
                <li><a href="index.php?action=search">Ajouter une review</a></li>
                <li class="see-profile"><a href="index.php?action=see-profile">Voir mon profil</a></li>
                <li><a href="index.php?action=logout">Déconnexion</a></li>
            </ul>
         </nav>
    <!--Si l'utilisateur ou l'admin ne sont pas connecté-->
    <?php elseif(!$this -> is_connect()): ?>
        <!--Logo blanc-->
        <div class="for-flex">
            <a href="index.php"><img src="public/images/logo_title_bgless.png" alt="Logo" id="logo"></a>
            <button id="drop-down-menu" class="check hoverblue"><i id="menu-icon" class="fa-solid fa-bars"></i></button>
        </div>
        <nav class="hidden-nav">
            <ul class="menu">
                <li><a href="index.php?action=login">Se connecter</a></li>
            </ul>
        </nav>
    <?php endif; ?>
</header>
<main>
    <?php require $template.".phtml" ?>
</main>
<script src="public/js/mobile_menu.js"></script>
</body>
</html>